# appveyor file
# http://www.appveyor.com/docs/appveyor-yml
version: "{build}"

os: Visual Studio 2017

# Test against this version of Node.js
environment:
  nodejs_version: "7"
platform: x64

init:
  - git config --global core.autocrlf input

cache:
 - "%LOCALAPPDATA%\\Yarn"

build_script:
  - yarn start

test: off
